name: open_file
description: A plug-in that can call native APP to open files with string result in flutter, support iOS(UTI) / android(intent) / PC(ffi) / web(dart:html)
version: 3.5.7
repository: https://github.com/crazecoder/open_file

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  open_file_android: ^1.0.3
  open_file_web: ^0.0.3
  open_file_ios: ^1.0.2
  open_file_mac: ^1.0.1
  open_file_windows: ^0.0.2
  open_file_linux: ^0.0.4
  open_file_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: open_file_android
      ios:
        default_package: open_file_ios
      web:
        default_package: open_file_web
      macos:
        default_package: open_file_mac
      windows:
        default_package: open_file_windows
      linux:
        default_package: open_file_linux

