name: open_file_platform_interface
description:  A common platform interface for the open_file plugin.
repository: https://github.com/crazecoder/open_file/open_file_platform_interface
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.10.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
